/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c45e710ab7b472f3114e2491c778dfe9)
interface __BaseEnv_Env {
	DB: D1Database;
	HERMES_PSTN_TOKEN: string;
	VOBIZ_BRIDGE_RELAY_TOKEN: string;
	VOBIZ_BRIDGE_SECRET: string;
	VOBIZ_AUTH_ID: string;
	VOBIZ_AUTH_TOKEN: string;
	VOBIZ_NUMBER: string;
	VOBIZ_PUBLIC_BASE_URL: string;
	VOBIZ_BRIDGE_WSS_URL: string;
	VOBIZ_OUTBOUND_ENABLED: string;
	VOBIZ_ALLOWED_DESTINATIONS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "HERMES_PSTN_TOKEN" | "VOBIZ_BRIDGE_RELAY_TOKEN" | "VOBIZ_BRIDGE_SECRET" | "VOBIZ_AUTH_ID" | "VOBIZ_AUTH_TOKEN" | "VOBIZ_NUMBER" | "VOBIZ_PUBLIC_BASE_URL" | "VOBIZ_BRIDGE_WSS_URL" | "VOBIZ_OUTBOUND_ENABLED" | "VOBIZ_ALLOWED_DESTINATIONS">> {}
}
