/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: eb367d5d29b891a91fc71952ac48e721)
interface __BaseEnv_Env {
	AUDIO: R2Bucket;
	DB: D1Database;
	HERMES_PRIVATE: Fetcher;
	APNS_BUNDLE_ID: "com.chirag.agentcaller";
	PAIRING_TTL_SECONDS: "900";
	AUDIO_MAX_BYTES: "5000000";
	AUDIO_TTL_SECONDS: "3600";
	LIVE_VOICE_ENABLED: "true";
	XAI_VOICE_MODEL: "grok-voice-think-fast-2.0";
	XAI_VOICE: "eve";
	HERMES_VOICE_TOOLSETS: "web,session_search";
	APNS_TEAM_ID: string;
	APNS_KEY_ID: string;
	APNS_PRIVATE_KEY: string;
	SCHEDULER: DurableObjectNamespace<import("./src/index").RelayScheduler>;
	HERMES_COORDINATOR: DurableObjectNamespace<import("./src/index").HermesInstallationCoordinator>;
	HERMES_WORKFLOW: Workflow<Parameters<import("./src/index").HermesOperationWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RelayScheduler" | "HermesInstallationCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APNS_BUNDLE_ID" | "PAIRING_TTL_SECONDS" | "AUDIO_MAX_BYTES" | "AUDIO_TTL_SECONDS" | "LIVE_VOICE_ENABLED" | "XAI_VOICE_MODEL" | "XAI_VOICE" | "HERMES_VOICE_TOOLSETS" | "APNS_TEAM_ID" | "APNS_KEY_ID" | "APNS_PRIVATE_KEY">> {}
}
